// Kedayam — phishing-classifier weights (AUTO-GENERATED by bun run train:classifier).
//
// DO NOT edit by hand. Host-shape weights are FITTED on a labeled corpus
// (6000 phishing + 6000 benign); the runtime-only features
// (notHttps, hasPasswordField, crossOriginForm, manyExternalScripts, obfuscation) keep fixed expert priors because a
// URL-only corpus can't fit them. Measured metrics live in public/kedayam-classifier-eval.json.
export const BIAS = -1.519;
export const WEIGHTS = Object.freeze({
  notHttps: 1.1,
  hasPasswordField: 1,
  crossOriginForm: 1.7,
  manyExternalScripts: 0.7,
  obfuscation: 1.2,
  punycode: 0,
  abusedTld: 2.0011,
  manySubdomains: 1.4262,
  hostDigitsRatio: 9.0909,
  hostHyphens: 0.8407,
  lureTokens: 0.2319,
  brandInSubdomain: 0,
});
export const CLASSIFIER_META = Object.freeze({
  corpus: { phishing: 6000, benign: 6000, level: "host-url-shape" },
  fittedFeatures: [
    "punycode",
    "abusedTld",
    "manySubdomains",
    "hostDigitsRatio",
    "hostHyphens",
    "lureTokens",
    "brandInSubdomain",
  ],
  fixedPriorFeatures: [
    "notHttps",
    "hasPasswordField",
    "crossOriginForm",
    "manyExternalScripts",
    "obfuscation",
  ],
  metrics: {
    warn: {
      threshold: 0.8,
      precision: 0.9798,
      recall: 0.6178,
      f1: 0.7578,
      falsePositiveRate: 0.014,
      accuracy: 0.7933,
      confusion: { tp: 776, fp: 16, tn: 1128, fn: 480 },
    },
    block: {
      threshold: 0.92,
      precision: 0.9909,
      recall: 0.5183,
      f1: 0.6806,
      falsePositiveRate: 0.0052,
      accuracy: 0.7454,
      confusion: { tp: 651, fp: 6, tn: 1138, fn: 605 },
    },
  },
});
